var L3 = require('..');

[
 L3,
 L3.True,
 L3.False,
 L3.Nil,
 L3.Nil.whenEquals(L3.Nil),
 L3.Nil.whenEquals(L3.Nil).then(),
 L3.Nil.whenNotEquals(L3.Nil),
 L3.Nil.whenNotEquals(L3.Nil).then(),
 L3.Nil.whenTrue(),
 L3.Nil.whenTrue().whenNil(),
 L3.Nil.whenTrue().whenFalse(),
 L3.Nil.whenNotTrue(),
 L3.Nil.whenFalse(),
 L3.Nil.whenFalse().whenNil(),
 L3.Nil.whenFalse().whenTrue(),
 L3.Nil.whenNotFalse(),
 L3.Nil.whenNil(),
 L3.Nil.whenNil().whenFalse(),
 L3.Nil.whenNil().whenTrue(),
 L3.Nil.whenNotNil(),
 L3.of(5),
 L3.of(5).whenTrue(),
 L3.of(5).whenTrue().whenNil(),
 L3.of(5).whenTrue().whenFalse(),
 L3.of(5).whenNotTrue(),
 L3.of(5).whenFalse(),
 L3.of(5).whenFalse().whenNil(),
 L3.of(5).whenFalse().whenTrue(),
 L3.of(5).whenNotFalse(),
 L3.of(5).whenNil(),
 L3.of(5).whenNil().whenFalse(),
 L3.of(5).whenNil().whenTrue(),
 L3.of(5).whenNotNil(),
 L3.test(L3.Nil),
 L3.test(L3.Nil).ok(() => {}),
 L3.test(L3.Nil).fail(() => {})
].forEach((obj, n) => console.log(n + 1, ' - ', obj.typename, '[', Object.keys(obj).sort().join(', '), ']'))

